Library\MainBundle\Entity\Book:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        year:
            type: smallint
        path:
            type: string
            length: 255
        author:
            type: string
            length: 255
        publishing:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
    manyToOne:
        category:
            targetEntity: Library\MainBundle\Entity\Category
            inversedBy: books
            joinColumn:
                name: category_id
                referencedColumName: id
