Library\MainBundle\Entity\Category:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
        books:
            targetEntity: Library\MainBundle\Entity\Book
            mappedBy: category
