Library\MainBundle\Entity\LibraryCard:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: datetime
        returnDate:
            type: datetime
            nullable: TRUE
    lifecycleCallbacks:
        prePersist: [ setCurrentDate ]
    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            inversedBy: libraryCard
            joinColumn:
                name: user_id
                referencedColumName: id
        book:
            targetEntity: Library\MainBundle\Entity\Book
            inversedBy: libraryCards
            joinColumn:
                name: book_id
                referencedColumName: id
