homepage:
    path:     /
    defaults: { _controller: LibraryMainBundle:Main:index }

show_books:
    path:   /showBooks/{page}
    defaults: { _controller: LibraryMainBundle:Book:showBooks, page: 1 }

not_found:
    path:   /notfound
    defaults: { _controller: LibraryMainBundle:Book:notFound }

show_library_card:
    path:   /libraryCard
    defaults: { _controller: LibraryMainBundle:LibraryCard:show }

find_books:
    path:   /find
    defaults: { _controller: LibraryMainBundle:FindBooks:find }

show_search_result:
    path:   /searchResult/{page}
    defaults: { _controller: LibraryMainBundle:FindBooks:showSearchResult }

borrow_book:
    path:   /borrow/id={id}
    defaults: { _controller: LibraryMainBundle:LibraryCard:borrow }

borrow_confirmed:
    path:   /borrowed/id={id}
    defaults: { _controller: LibraryMainBundle:LibraryCard:succesfull }

return_book:
    path:   /return/id={cardId}
    defaults: { _controller: LibraryMainBundle:LibraryCard:returnBook }

returned:
    path:   /bookReturned
    defaults: { _controller: LibraryMainBundle:LibraryCard:returned }

not_admin:
    path:   /notAdmin
    defaults: { _controller: LibraryMainBundle:Main:notAdmin }