services:
    sonata.admin.slider:
        class: Library\MainBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Biblioteka", label: "Ksiazki" }
        arguments:
            - ~
            - Library\MainBundle\Entity\Book
            - ~
        calls:
            - [ setTranslationDomain, [LibraryMainBundle]]
    library.book_agent:
        class: Library\MainBundle\Model\BookAgent
        arguments: [ "@doctrine.orm.entity_manager" ]
    library.librarycard_agent:
        class: Library\MainBundle\Model\LibraryCardAgent
        arguments: [ "@doctrine.orm.entity_manager" ]