services:
    sonata.admin.slider:
        class: Library\MainBundle\Admin\BookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Biblioteka", label: "Ksiazki" }
        arguments:
            - ~
            - Library\MainBundle\Entity\Book
            - ~
        calls:
            - [ setTranslationDomain, [LibraryMainBundle]]
