<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $libraryCard;

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
        $this->libraryCard = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add libraryCard
     *
     * @param \Library\MainBundle\Entity\LibraryCard $libraryCard
     * @return User
     */
    public function addLibraryCard(\Library\MainBundle\Entity\LibraryCard $libraryCard)
    {
        $this->libraryCard[] = $libraryCard;

        return $this;
    }

    /**
     * Remove libraryCard
     *
     * @param \Library\MainBundle\Entity\LibraryCard $libraryCard
     */
    public function removeLibraryCard(\Library\MainBundle\Entity\LibraryCard $libraryCard)
    {
        $this->libraryCard->removeElement($libraryCard);
    }

    /**
     * Get libraryCard
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getLibraryCard()
    {
        return $this->libraryCard;
    }
}
