services:
    library_user.registration.form.type:
        class: Library\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: library_user_registration }
